### ISSUE TITLE
Sugerencias

### ISSUE THREAD

**Issue by tanrax** [brunocascio/docker-espanol#6]
Es maravilloso el resumen, te felicito.

Pero aún puede ser mejor, creo que le falta los siguientes temas:

- Como subir tu imagen a un repositorio git.
- Como desplegar tu imagen en un servidor propio.

**Comment by brunocascio** [comment]
Gracias!

Versionar las imágenes pienso que es más bien algo relacionado a git y no a Docker.

Desplegar una imagen en un servidor propio, está implícitamente hecho con el comando `docker run`. De todas formas podría agregar documentación de cómo publicar una imagen para posteriormente utilizarla, o si prefieres agregarlo en un PR es bienvenido!

Gracias por el feedback!

**Comment by tanrax** [comment]
Un tema que encuentro poca documentación, o yo soy incapaz de identificarla, es la posibilidad de crear una imagen para subirla a un repositorio y compartirla con el equipo. Es vital para todos tener la misma información en la base de datos. Por lo que tal vez, y por supuesto puedo estar equivocado por mi poca experiencia, sería interesante para un nuevo capitulo.

Intentaré realizar algún PR en cuento adquiera un poco más de experiencia. Gracias!!!

**Comment by brunocascio** [comment]
Unos de los principales componentes del ecosistema Docker, es Docker Hub que es allí donde se almacenan las imágenes que decidimos compartir. En la misma existe la posibilidad de crear "organizaciones" (equipos) en donde cada uno puede colaborar.

En Git lo que de versiona es el Dockerfile y los archivos necesarios para construir una imagen. Pero la imagen "buildeada" es almacenada y versionada en DockerHub.

**Comment by tanrax** [comment]
Gracias por la información :)
